-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 16:20:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema incidencias_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `incidencias_db` DEFAULT CHARACTER SET utf8 ;
USE `incidencias_db` ;

-- -----------------------------------------------------
-- Table `incidencias_db`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`provincias` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`municipios` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `provincias_id` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `provincias_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_municipios_provincias1_idx` (`provincias_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `incidencias_db`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`barrios` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `municipios_id` SMALLINT NOT NULL,
  PRIMARY KEY (`id`, `municipios_id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_barrios_municipios1_idx` (`municipios_id` ASC) VISIBLE,
  CONSTRAINT `fk_barrios_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `incidencias_db`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`etiquetas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('default', 'reportero', 'validador', 'admin') NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarioscol_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`incidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`incidencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_ocurrencia` DATETIME NOT NULL,
  `coordenadas` POINT NOT NULL,
  `esta_aprobada` TINYINT NOT NULL DEFAULT 0,
  `cant_muertos` INT NULL,
  `cant_heridos` INT NULL,
  `cant_perdidas` DECIMAL(15,2) NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `codigo_grupo` VARCHAR(100) NULL,
  `provincias_id` TINYINT NOT NULL,
  `municipios_id` SMALLINT NOT NULL,
  `barrios_id` MEDIUMINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `provincias_id`, `usuarios_id`),
  INDEX `fk_incidencias_provincias1_idx` (`provincias_id` ASC) VISIBLE,
  INDEX `fk_incidencias_municipios1_idx` (`municipios_id` ASC) VISIBLE,
  INDEX `fk_incidencias_barrios1_idx` (`barrios_id` ASC) VISIBLE,
  INDEX `fk_incidencias_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidencias_provincias1`
    FOREIGN KEY (`provincias_id`)
    REFERENCES `incidencias_db`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencias_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `incidencias_db`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencias_barrios1`
    FOREIGN KEY (`barrios_id`)
    REFERENCES `incidencias_db`.`barrios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencias_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `incidencias_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(500) NOT NULL,
  `incidencias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `incidencias_id`),
  INDEX `fk_fotos_incidencias1_idx` (`incidencias_id` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_incidencias1`
    FOREIGN KEY (`incidencias_id`)
    REFERENCES `incidencias_db`.`incidencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `incidencias_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `incidencias_id`, `usuarios_id`),
  INDEX `fk_comentarios_incidencias1_idx` (`incidencias_id` ASC) VISIBLE,
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_incidencias1`
    FOREIGN KEY (`incidencias_id`)
    REFERENCES `incidencias_db`.`incidencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `incidencias_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`incidencias_etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`incidencias_etiquetas` (
  `incidencias_id` INT NOT NULL,
  `etiquetas_id` INT NOT NULL,
  PRIMARY KEY (`incidencias_id`, `etiquetas_id`),
  INDEX `fk_incidencias_has_etiquetas_etiquetas1_idx` (`etiquetas_id` ASC) VISIBLE,
  INDEX `fk_incidencias_has_etiquetas_incidencias1_idx` (`incidencias_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidencias_has_etiquetas_incidencias1`
    FOREIGN KEY (`incidencias_id`)
    REFERENCES `incidencias_db`.`incidencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencias_has_etiquetas_etiquetas1`
    FOREIGN KEY (`etiquetas_id`)
    REFERENCES `incidencias_db`.`etiquetas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`correciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`correciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valores` JSON NOT NULL,
  `esta_aprobada` TINYINT NOT NULL DEFAULT 0,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `incidencias_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `incidencias_id`, `usuarios_id`),
  INDEX `fk_correciones_incidencias1_idx` (`incidencias_id` ASC) VISIBLE,
  INDEX `fk_correciones_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_correciones_incidencias1`
    FOREIGN KEY (`incidencias_id`)
    REFERENCES `incidencias_db`.`incidencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_correciones_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `incidencias_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `incidencias_db`.`roles_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidencias_db`.`roles_usuarios` (
  `roles_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `usuarios_id`),
  INDEX `fk_roles_has_usuarios_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_roles_has_usuarios_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_has_usuarios_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `incidencias_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `incidencias_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
